#!/bin/bash

go build -o built-out ./out/cmd/out
go build -o built-check ./check/cmd/check

curl -L https://cli.run.pivotal.io/stable?release=linux64-binary > cf-linux.tar.gz
tar -xvf cf-linux.tar.gz
