#!/bin/bash
# vim: set ft=sh

set -e

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

# run tests
(
    set -e

    cd $GOPATH/src/github.com/concourse/cf-resource

    export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
    export PATH=${PWD}/Godeps/_workspace/bin:$PATH

    go install github.com/onsi/ginkgo/ginkgo

    ginkgo -r -p "$@"
)

# build & download binaries
(
    set -e

    cd $GOPATH/src/github.com/concourse/autopilot

    export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
    export PATH=${PWD}/Godeps/_workspace/bin:$PATH

    go build -o autopilot github.com/concourse/autopilot
    mv autopilot $GOPATH/src/github.com/concourse/cf-resource
)

(
    set -e

    cd $GOPATH/src/github.com/concourse/cf-resource

    export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
    export PATH=${PWD}/Godeps/_workspace/bin:$PATH

    go build -o built-out ./out/cmd/out
    go build -o built-check ./check/cmd/check
)

(
    set -e

    tar -xvf cf-cli/cf-linux-amd64.tgz
    ls -R cf-cli
    mv cf-cli/cf $GOPATH/src/github.com/concourse/cf-resource
)

